[env:seeed_xiao_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200

[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = arduino
monitor_speed = 115200

[env:nucleo_g431rb]
platform = ststm32
board = nucleo_g431rb
framework = arduino
monitor_speed = 115200
