[platformio]
src_dir = .

[env:seeed_xiao_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0

[env:seeed_xiao_rp2040_native]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
build_flags = -DNATIVE_PWM
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0
