name: PlatformIO CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio

    - name: Cache Arduino CLI
      uses: actions/cache@v3
      with:
        path: ~/.arduino15
        key: ${{ runner.os }}-arduino-${{ hashFiles('examples/BEMF_Ramp_Test/BEMF_Ramp_Test.ino') }}
        restore-keys: |
          ${{ runner.os }}-arduino-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Build Root Project
      run: pio run

    - name: Build BEMF_Ramp_Test Example (PlatformIO)
      run: |
        cd examples/BEMF_Ramp_Test
        pio run

    - name: Build Marklin_Motor_Control Example (PlatformIO)
      run: |
        cd examples/Marklin_Motor_Control
        pio run

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v2

    - name: Install Arduino RP2040 Core & Libraries
      run: |
        arduino-cli core update-index --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
        arduino-cli core install rp2040:rp2040 --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
        arduino-cli lib install "PID"
        arduino-cli lib install "SerialCommands"

    - name: Compile BEMF_Ramp_Test (Arduino CLI)
      run: |
        arduino-cli compile --fqbn rp2040:rp2040:seeed_xiao_rp2040 examples/BEMF_Ramp_Test/BEMF_Ramp_Test.ino

    - name: Compile Marklin_Motor_Control (Arduino CLI)
      run: |
        arduino-cli compile --fqbn rp2040:rp2040:seeed_xiao_rp2040 examples/Marklin_Motor_Control/Marklin_Motor_Control.ino
